theme: jekyll-theme-cayman

title: Polo de Contenidos Digitales.
description: > # this means to ignore newlines until "baseurl:"
  Sitio de la Oficina TÃ©cnica del Polo de Contenidos Digitales.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://polodigital.github.io" # the base hostname & protocol for your site, e.g. http://example.com
